declare namespace _default {
    export { CATEGORIES };
    export { CLASSIFICATIONS };
    export { IDS };
    export { TYPES };
    export { getListByCategory };
    export { getListByClassification };
    export { getType };
}
export default _default;
declare namespace CATEGORIES {
    let ACID: string;
    let ADHESIVE: string;
    let ALLOY: string;
    let BASE: string;
    let CARBONATE: string;
    let CERAMIC: string;
    let CONSTRUCTION: string;
    let CRYSTAL: string;
    let ELECTROMECHANICAL: string;
    let ELECTRONICS: string;
    let ELECTRO_OPTICAL: string;
    let ENGINE_PART: string;
    let FABRIC: string;
    let FISSILE: string;
    let FLUORIDE: string;
    let FOOD: string;
    let GROWN_ORGANIC: string;
    let HULL_MODULE: string;
    let INGREDIENT: string;
    let INTEGRATION_MODULE: string;
    let MECHANISM: string;
    let METAL: string;
    let NITRATE: string;
    let NONMETAL: string;
    let ORGANIC: string;
    let ORGANIC_SUBSTRATE: string;
    let OXIDE: string;
    let PHOSPHATE: string;
    let POLYMER: string;
    let POWDER: string;
    let PROCESSED_GLASS: string;
    let PROCESSED_METAL: string;
    let PROPELLANT: string;
    let RARE_EARTH: string;
    let REFINED_FISSILE: string;
    let REFINED_GLASS: string;
    let REFINED_METAL: string;
    let REFINED_ORGANIC: string;
    let REFINED_RARE_EARTH: string;
    let REFINED_VOLATILE: string;
    let SALT: string;
    let SEMI_REFINED: string;
    let SHIP_HULL: string;
    let SHIP_PART: string;
    let SULFATE: string;
    let SULFIDE: string;
    let TOOL: string;
    let VOLATILE: string;
}
declare namespace CLASSIFICATIONS {
    let ASSEMBLY: string;
    let CROP: string;
    let MANUFACTURED_GOOD: string;
    let RAW_MATERIAL: string;
    let REFINED_MATERIAL: string;
}
declare namespace IDS {
    export let WATER: number;
    export let HYDROGEN: number;
    export let AMMONIA: number;
    export let NITROGEN: number;
    export let SULFUR_DIOXIDE: number;
    export let CARBON_DIOXIDE: number;
    export let CARBON_MONOXIDE: number;
    export let METHANE: number;
    export let APATITE: number;
    export let BITUMEN: number;
    export let CALCITE: number;
    export let FELDSPAR: number;
    export let OLIVINE: number;
    export let PYROXENE: number;
    export let COFFINITE: number;
    export let MERRILLITE: number;
    export let XENOTIME: number;
    export let RHABDITE: number;
    export let GRAPHITE: number;
    export let TAENITE: number;
    export let TROILITE: number;
    export let URANINITE: number;
    export let OXYGEN: number;
    export let DEIONIZED_WATER: number;
    export let RAW_SALTS: number;
    export let SILICA: number;
    export let NAPHTHA: number;
    export let SODIUM_BICARBONATE: number;
    export let IRON: number;
    export let COPPER: number;
    export let NICKEL: number;
    export let QUICKLIME: number;
    export let ACETYLENE: number;
    export let AMMONIUM_CARBONATE: number;
    export let TRIPLE_SUPERPHOSPHATE: number;
    export let PHOSPHATE_AND_SULFATE_SALTS: number;
    export let IRON_SULFIDE: number;
    export let LEAD_SULFIDE: number;
    export let TIN_SULFIDE: number;
    export let MOLYBDENUM_DISULFIDE: number;
    export let FUSED_QUARTZ: number;
    export let FIBERGLASS: number;
    export let BARE_COPPER_WIRE: number;
    export let CEMENT: number;
    export let SODIUM_CHLORIDE: number;
    export let POTASSIUM_CHLORIDE: number;
    export let BORAX: number;
    export let LITHIUM_CARBONATE: number;
    export let MAGNESIUM_CHLORIDE: number;
    export let PROPYLENE: number;
    export let SULFUR: number;
    export let STEEL: number;
    export let SILICON: number;
    export let NITRIC_ACID: number;
    export let SULFURIC_ACID: number;
    export let SOIL: number;
    export let FERROSILICON: number;
    export let WEATHERED_OLIVINE: number;
    export let OXALIC_ACID: number;
    export let SILVER: number;
    export let GOLD: number;
    export let TIN: number;
    export let IRON_OXIDE: number;
    export let SPIRULINA_AND_CHLORELLA_ALGAE: number;
    export let MOLYBDENUM_TRIOXIDE: number;
    export let SILICA_POWDER: number;
    export let SOLDER: number;
    export let FIBER_OPTIC_CABLE: number;
    export let STEEL_BEAM: number;
    export let STEEL_SHEET: number;
    export let STEEL_PIPE: number;
    export let STEEL_WIRE: number;
    export let ACRYLONITRILE: number;
    export let POLYPROPYLENE: number;
    export let MAGNESIUM: number;
    export let CHLORINE: number;
    export let SODIUM_CARBONATE: number;
    export let CALCIUM_CHLORIDE: number;
    export let BORIA: number;
    export let LITHIUM_SULFATE: number;
    export let HYDROCHLORIC_ACID: number;
    export let HYDROFLUORIC_ACID: number;
    export let PHOSPHORIC_ACID: number;
    export let BORIC_ACID: number;
    export let ZINC_OXIDE: number;
    export let NICKEL_OXIDE: number;
    export let MAGNESIA: number;
    export let ALUMINA: number;
    export let SODIUM_HYDROXIDE: number;
    export let POTASSIUM_HYDROXIDE: number;
    export let SOYBEANS: number;
    export let POTATOES: number;
    export let AMMONIUM_OXALATE: number;
    export let RARE_EARTH_SULFATES: number;
    export let FERROCHROMIUM: number;
    export let YELLOWCAKE: number;
    export let ALUMINA_CERAMIC: number;
    export let AUSTENITIC_NICHROME: number;
    export let COPPER_WIRE: number;
    export let SILICON_WAFER: number;
    export let STEEL_CABLE: number;
    export let POLYACRYLONITRILE: number;
    export let NATURAL_FLAVORINGS: number;
    export let PLATINUM: number;
    export let LITHIUM_CHLORIDE: number;
    export let ZINC: number;
    export let EPICHLOROHYDRIN: number;
    export let BISPHENOL_A: number;
    export let RARE_EARTH_OXIDES: number;
    export let AMMONIUM_CHLORIDE: number;
    export let ALUMINIUM: number;
    export let CALCIUM: number;
    export let SODIUM_CHROMATE: number;
    export let LEACHED_COFFINITE: number;
    export let URANYL_NITRATE: number;
    export let FLUORINE: number;
    export let SODIUM_TUNGSTATE: number;
    export let FERRITE: number;
    export let DIODE: number;
    export let LASER_DIODE: number;
    export let BALL_VALVE: number;
    export let ALUMINIUM_BEAM: number;
    export let ALUMINIUM_SHEET: number;
    export let ALUMINIUM_PIPE: number;
    export let POLYACRYLONITRILE_FABRIC: number;
    export let COLD_GAS_THRUSTER: number;
    export let COLD_GAS_TORQUE_THRUSTER: number;
    export let CARBON_FIBER: number;
    let FOOD_1: number;
    export { FOOD_1 as FOOD };
    export let SMALL_PROPELLANT_TANK: number;
    export let BOROSILICATE_GLASS: number;
    export let BALL_BEARING: number;
    export let LARGE_THRUST_BEARING: number;
    export let BORON: number;
    export let LITHIUM: number;
    export let EPOXY: number;
    export let NEODYMIUM_OXIDE: number;
    export let YTTRIA: number;
    export let SODIUM_DICHROMATE: number;
    export let NOVOLAK_PREPOLYMER_RESIN: number;
    export let FERROMOLYBDENUM: number;
    export let AMMONIUM_DIURANATE: number;
    export let AMMONIUM_PARATUNGSTATE: number;
    export let ENGINE_BELL: number;
    export let STEEL_TRUSS: number;
    export let ALUMINIUM_HULL_PLATE: number;
    export let ALUMINIUM_TRUSS: number;
    export let CARGO_MODULE: number;
    export let PRESSURE_VESSEL: number;
    export let PROPELLANT_TANK: number;
    export let STAINLESS_STEEL: number;
    export let BARE_CIRCUIT_BOARD: number;
    export let FERRITE_BEAD_INDUCTOR: number;
    export let CORE_DRILL_BIT: number;
    export let CORE_DRILL_THRUSTER: number;
    export let PARABOLIC_DISH: number;
    export let PHOTOVOLTAIC_PANEL: number;
    export let LIPO_BATTERY: number;
    export let NEODYMIUM_TRICHLORIDE: number;
    export let CHROMIA: number;
    export let PHOTORESIST_EPOXY: number;
    export let URANIUM_DIOXIDE: number;
    export let TUNGSTEN: number;
    export let SHUTTLE_HULL: number;
    export let LIGHT_TRANSPORT_HULL: number;
    export let CARGO_RING: number;
    export let HEAVY_TRANSPORT_HULL: number;
    export let TUNGSTEN_POWDER: number;
    export let HYDROGEN_PROPELLANT: number;
    export let STAINLESS_STEEL_SHEET: number;
    export let STAINLESS_STEEL_PIPE: number;
    export let CCD: number;
    export let COMPUTER_CHIP: number;
    export let CORE_DRILL: number;
    export let NEODYMIUM: number;
    export let CHROMIUM: number;
    export let URANIUM_TETRAFLUORIDE: number;
    export let PURE_NITROGEN: number;
    export let ND_YAG_LASER_ROD: number;
    export let NICHROME: number;
    export let NEODYMIUM_MAGNET: number;
    export let UNENRICHED_URANIUM_HEXAFLUORIDE: number;
    export let HIGHLY_ENRICHED_URANIUM_HEXAFLUORIDE: number;
    export let ND_YAG_LASER: number;
    export let THIN_FILM_RESISTOR: number;
    export let HIGHLY_ENRICHED_URANIUM_POWDER: number;
    export let LEACHED_FELDSPAR: number;
    export let ROASTED_RHABDITE: number;
    export let RHABDITE_SLAG: number;
    export let POTASSIUM_CARBONATE: number;
    export let HYDROGEN_HEPTAFLUOROTANTALATE_AND_NIOBATE: number;
    export let LEAD: number;
    export let POTASSIUM_FLUORIDE: number;
    export let POTASSIUM_HEPTAFLUOROTANTALATE: number;
    export let DIEPOXY_PREPOLYMER_RESIN: number;
    export let TANTALUM: number;
    export let PEDOT: number;
    export let POLYMER_TANTALUM_CAPACITOR: number;
    export let SURFACE_MOUNT_DEVICE_REEL: number;
    export let CIRCUIT_BOARD: number;
    export let BRUSHLESS_MOTOR_STATOR: number;
    export let BRUSHLESS_MOTOR_ROTOR: number;
    export let BRUSHLESS_MOTOR: number;
    export let LANDING_LEG: number;
    export let LANDING_AUGER: number;
    export let PUMP: number;
    export let RADIO_ANTENNA: number;
    export let FIBER_OPTIC_GYROSCOPE: number;
    export let STAR_TRACKER: number;
    export let COMPUTER: number;
    export let CONTROL_MOMENT_GYROSCOPE: number;
    export let ROBOTIC_ARM: number;
    export let BERYLLIUM_CARBONATE: number;
    export let BERYLLIA: number;
    export let BERYLLIA_CERAMIC: number;
    export let NEON: number;
    export let HEAT_EXCHANGER: number;
    export let TURBOPUMP: number;
    export let NEON_FUEL_SEPARATOR_CENTRIFUGE: number;
    export let FUEL_MAKE_UP_TANK: number;
    export let NEON_MAKE_UP_TANK: number;
    export let LIGHTBULB_END_MODERATORS: number;
    export let FUSED_QUARTZ_LIGHTBULB_TUBE: number;
    export let REACTOR_PLUMBING_ASSEMBLY: number;
    export let FLOW_DIVIDER_MODERATOR: number;
    export let NUCLEAR_LIGHTBULB: number;
    export let COMPOSITE_OVERWRAPPED_REACTOR_SHELL: number;
    export let CLOSED_CYCLE_GAS_CORE_NUCLEAR_REACTOR_ENGINE: number;
    export let HABITATION_MODULE: number;
    export let MOBILITY_MODULE: number;
    export let FLUIDS_AUTOMATION_MODULE: number;
    export let SOLIDS_AUTOMATION_MODULE: number;
    export let TERRAIN_INTERFACE_MODULE: number;
    export let AVIONICS_MODULE: number;
    export let ESCAPE_MODULE: number;
    export let ATTITUDE_CONTROL_MODULE: number;
    export let POWER_MODULE: number;
    export let THERMAL_MODULE: number;
    export let PROPULSION_MODULE: number;
}
declare const TYPES: {
    [x: number]: {
        i: number;
        name: string;
        classification: string;
        category: string;
        massPerUnit: number;
        volumePerUnit: number;
        isAtomic: boolean;
    };
};
declare function getListByCategory(category: any): number[];
declare function getListByClassification(classification: any): number[];
declare function getType(type: any): {
    i: number;
    name: string;
    classification: string;
    category: string;
    massPerUnit: number;
    volumePerUnit: number;
    isAtomic: boolean;
};
